Feat/add hero
misamina30/BLOG_UI_TEMPLATE pull request #2
Opened 2022-12-27 18:10 UTC by misamina30

hola Neri buenas tardes, se agrego, el hero y necesito aprobacion.... ya comode todo alfabeticamente y las clases igual espero pasar de una jaja

2022-12-27 21:36 UTC, neriheredia requested changes

2022-12-27 21:36 UTC, neriheredia commented on src/App.css
> +}
orden alfabético

2022-12-27 21:36 UTC, neriheredia commented on src/App.jsx
> +
quitar la linea en blanco

2022-12-27 21:36 UTC, neriheredia commented on src/components/navbar/Navbar.module.css
> +}
orden alfabético

2022-12-27 21:36 UTC, neriheredia commented on src/components/navbar/Navbar.module.css
> +	/* padding: 0 10px; */
eliminar comentario

2022-12-27 21:36 UTC, neriheredia commented on src/components/navbar/navbarCenter/NavbarCenter.module.css
> +}
en ingles y orden alfabetico

2022-12-27 21:36 UTC, neriheredia commented on src/components/navbar/navbarLeft/NavbarLeft.module.css
> +	margin-right: 10px;
Orden alfabético y escribir clase en ingles

2022-12-27 21:36 UTC, neriheredia commented on src/components/navbar/navbarRight/NavbarRight.module.css
> +	justify-content: center;
orden alfabético

2023-01-05 17:47 UTC, closed without merging

2023-01-05 17:47 UTC, misamina30 commented
elimino